### ISSUE TITLE
Radium and modifiers 

### ISSUE THREAD

**Issue by tw-360vier** [halt-hammerzeit/react-styling#1]
When i run your DroidList example, radium's prefixer complains about the nested modifiers:
```
Unsupported CSS property "droid" in component "DroidList"               prefixer.js?715e:377 
Unsupported CSS property "first" in component "DroidList"               prefixer.js?715e:377 
Unsupported CSS property "last" in component "DroidList"               prefixer.js?715e:377 
[...]
```
Is there a trick to make this work or do i have to just ignore these messages?

**Comment by halt-hammerzeit** [comment]
I'll write the 'trick' and release a new version

**Comment by halt-hammerzeit** [comment]
Ok, google, try this new version 1.4.0 with this feature:
https://github.com/halt-hammerzeit/react-styling#nesting

**Comment by halt-hammerzeit** [comment]
Updated droids example:
https://github.com/halt-hammerzeit/react-styling#radium

**Comment by tw-360vier** [comment]
wow you're fast! thanks! works perfectly.

btw react-styling has impoved my react workflow a lot.
With webstorm language injections i can even have my css inside .js files highlighted and autocompleted.
Nice!
