### ISSUE TITLE
How to styling from import/require css

### ISSUE THREAD

**Issue by NgKhanh** [halt-hammerzeit/react-styling#5]
hello, how can I parse a css to style object from import/require css

```
import styler from 'react-styling'
import mycss from '../assets/style.css'
const styles = styler(mycss )
```
or
`const styles = styler('../assets/style.css')`

And, can do that with less/sass ?

**Comment by halt-hammerzeit** [comment]
You can't `require()` CSS files in Node.js.
Try `fs.readFileSync('../assets/style.css', 'utf-8')` **if** you're on Node.js.
But `fs` won't work in the browser.

**Comment by halt-hammerzeit** [comment]
And I personally would suggest you use Webpack.
You can then write your own `css-file-loader` if you're skilled enought.
