### ISSUE TITLE
Getting style as [object Object] while nesting even with 'flat'

### ISSUE THREAD

**Issue by Aykelith** [halt-hammerzeit/react-styling#6]
I have `import { flat as styler } from 'react-styling';` and nested code like:

    logoImg
        @media (max-width: 500px)
            width: 90%`

but still getting `style="@media (max-width: 500px):[object Object];"` as final result.

**Comment by halt-hammerzeit** [comment]
Works as expected:

```js

	it('@media', function()
	{
		const style = styler
		`
			logoImg
				@media (max-width: 500px)
					width: 90%
		`

		const object =
		{
			logoImg:
			{
				'@media (max-width: 500px)':
				{
					width: '90%'
				}
			}
		}

		style.should.deep.equal(object)
	})
```
